[build]
  # No build command needed - static HTML site
  command = "echo 'No build needed - deploying static files'"
  
  # Directory to publish (current directory)
  publish = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Don't redirect - these are direct HTML pages, not a SPA
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
